language: node_js
node_js:
  - "6"
notifications:
  slack:
    secure: k7BOhpEMA+69A9rC3rIivOw9MCUpiCfzUWIifASKzAY5pC8mVvNq7vQkBhLTUQaKza7lDl7WJlzY2bI1+N9i52PJK3e0KHw67YbQWUW0xHOWATwkos4TkQSaUAfwLRYzYvPNkldGnfDHY/PcPAq+7kM06QEel0tP4aOXYGk0SFaOUw2GRNB4izhzsS3FWnd+Xtug8bDGNhjyqNwY3EeSaM8ednn6fH+zSgcK1iaoXRQfyKjvS9Xn0sRvDmwx0pgncTHp2riJDLwum+iCMRpCAV0+DE8Y+rIxc3aYXx32Bvyt3umGMz5WKasH4N9vGfNtRCPnPJ5V0g0v3jAOD1l1X0stVydaRWAn5L5f5IPyrqPp4otw8eE5DQcmH2eHB1f9lf4QgfH5JZtUwES3lIquThthTZY9jy3O95L8rr1Wkds8qd3rULPc8H9fqnfGq/0+XuFOvp1XO47lEmzmQNPSwvekqc7B+gH3dxteIrSDjQOXKTzW1WdxlmLkER7b5bTQO+JSulRynnkgoWDjXbzXPW0Y+Wmt5PVKyJwBtBpe9wFvpnQWTW+yEjSLAlGMzsmUfN4zCs2bRywQndcc0TH3aAwIhSMvU23aV7bd3Izzl274z3vt+DDCMOcFsXRD8HyLUdo9r5llrZIWqjJwHpWtlfhNz8HOZlBnIpS8aSM7Zgk=
